### ISSUE TITLE
Hi，我是从 csdn看到你的博客的，想邀请你入驻掘金技术社区

### ISSUE THREAD

**Issue by itcodes** [ChovaVea/chova#1]
Hi，我是从 csdn看到你的博客的，想邀请你入驻掘金技术社区。方便加下你的微信哈。

**Comment by ChovaVea** [comment]
嗯，可以加一下我的微信,微信号chova_vea

发自我的iPhone

在 2021年3月17日，上午1:01，优弧 ***@***.***> 写道：

﻿

Hi，我是从 csdn看到你的博客的，想邀请你入驻掘金技术社区。方便加下你的微信哈。
